services: # Секция, где мы объявляем все наши сервисы (контейнеры)
  
  db: # Наш второй сервис - база данных PostgreSQL
    image: postgres:15-alpine # Используем официальный образ Postgres на Alpine
    container_name: postgres-container
    environment: # Критически важные переменные для первоначальной настройки Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" # Пробрасываем порт БД, чтобы можно было подключиться с хоста (например, DBeaver, pgAdmin)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Сохраняем данные БД в именованном томе, чтобы они не пропали после остановки контейнера
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql # Запуск файла для создания таблиц

# Объявляем тома, которые используются нашими сервисами
volumes:
  postgres_data: # Именованный том для хранения данных PostgreSQL